### ISSUE TITLE
Embeds: annotation and cursor misaligned

### ISSUE THREAD

**Issue by emro** [VALIS-software/valis-hpgv#20]
When Valis visualizations are embedded in a page where they are not full-width, the cursor is not aligned with the signal annotation. See here →

![screen shot 2019-02-01 at 1 37 18 pm](https://user-images.githubusercontent.com/2887343/52151078-b774ab00-2626-11e9-88d1-b3325d3d98a1.png)

**Comment by haxiomic** [comment]
Thanks for reporting this one @emro! Turned out to be a typo: 6f5c30d7d79d3d5524887d0499e51a08e6494caf
