### ISSUE TITLE
Preprocessing Tool: Fatal error on some files

### ISSUE THREAD

**Issue by emro** [VALIS-software/valis-hpgv#22]
I tried to process the following three files using the file converter tool and each of them resulted in a fatal error:
- Human GRCh38 GENCODE v29 GFF3: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gff3.gz
- Human hg19 GENCODE v29 GFF3: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh37_mapping/gencode.v29lift37.annotation.gff3.gz
- Mouse mm10 GENCODE M21 GFF3: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M21/gencode.vM21.annotation.gff3.gz

I'm not sure exactly what the issue is, because I have been able to process other large GFF3 files from GENCODE successfully.

**Comment by haxiomic** [comment]
Thanks for the report @emro!

The crash was due to the converter's memory running out of space – I can tweak things so that it process large files incrementally rather than all in one go

**Comment by haxiomic** [comment]
This should be fixed now :)
